import { EcoPill, EcoPillCategory, EcoDifficulty } from '../modules/academy/entities/eco-pill.entity';

export const ecoPillsSeeds: Partial<EcoPill>[] = [
  {
    slug: 'fleet-maintenance-101',
    title: 'Fleet Maintenance 101',
    excerpt: 'Learn optimal maintenance schedules for maximum fuel efficiency',
    category: EcoPillCategory.FLEET_MANAGEMENT,
    difficulty: EcoDifficulty.BEGINNER,
    durationMin: 15,
    content: 'Proper vehicle maintenance is essential for fuel efficiency. Regular oil changes, tire pressure checks, and filter replacements can improve fuel economy by up to 10%.',
    accessLevel: 'free',
    published: true,
  },
  {
    slug: 'route-optimization-strategies',
    title: 'Route Optimization Strategies',
    excerpt: 'Advanced techniques for reducing miles driven and fuel costs',
    category: EcoPillCategory.ECO_DRIVING,
    difficulty: EcoDifficulty.INTERMEDIATE,
    durationMin: 25,
    content: 'Master route planning to minimize distance and fuel consumption. Learn how to use CENTRAL BUY tools for real-time route optimization.',
    accessLevel: 'particular',
    published: true,
  },
  {
    slug: 'eco-driving-habits',
    title: 'Eco-Driving Habits for Professionals',
    excerpt: 'Develop driving patterns that reduce emissions and save fuel',
    category: EcoPillCategory.ECO_DRIVING,
    difficulty: EcoDifficulty.BEGINNER,
    durationMin: 20,
    content: 'Smooth acceleration, maintaining steady speeds, and proper tire inflation can reduce fuel consumption by 5-15%. Learn the science behind efficient driving.',
    accessLevel: 'free',
    published: true,
  },
  {
    slug: 'carbon-emissions-tracking',
    title: 'Carbon Emissions Tracking & Reporting',
    excerpt: 'Monitor and reduce your fleet\'s environmental impact',
    category: EcoPillCategory.EMISSIONS,
    difficulty: EcoDifficulty.INTERMEDIATE,
    durationMin: 18,
    content: 'Understand how to calculate carbon emissions from fuel consumption. Track progress toward sustainability goals with CENTRAL BUY analytics.',
    accessLevel: 'empresa',
    published: true,
  },
  {
    slug: 'fuel-tank-efficiency',
    title: 'Maximizing Fuel Tank Efficiency',
    excerpt: 'Best practices for refueling and fuel storage',
    category: EcoPillCategory.FLEET_MANAGEMENT,
    difficulty: EcoDifficulty.BEGINNER,
    durationMin: 12,
    content: 'Learn when and how to refuel for maximum efficiency. Discover the impact of fuel additives and storage conditions on performance.',
    accessLevel: 'free',
    published: true,
  },
  {
    slug: 'advanced-fleet-analytics',
    title: 'Advanced Fleet Analytics & Reporting',
    excerpt: 'Deep dive into fleet performance metrics and KPIs',
    category: EcoPillCategory.FLEET_MANAGEMENT,
    difficulty: EcoDifficulty.ADVANCED,
    durationMin: 35,
    content: 'Master the CENTRAL BUY dashboard for advanced analytics. Learn to interpret fuel efficiency metrics, cost per mile, and ROI calculations for your fleet.',
    accessLevel: 'empresa',
    published: true,
  },
  {
    slug: 'sustainability-certification',
    title: 'ISO 14001 & Sustainability Certifications',
    excerpt: 'Align your fleet operations with international sustainability standards',
    category: EcoPillCategory.SUSTAINABILITY,
    difficulty: EcoDifficulty.ADVANCED,
    durationMin: 45,
    content: 'Understand how fuel management contributes to ISO 14001 compliance. Learn to document and report sustainability metrics for certifications.',
    accessLevel: 'empresa',
    published: true,
  },
  {
    slug: 'alternative-fuel-sources',
    title: 'Alternative Fuels & Hybrid Technologies',
    excerpt: 'Explore next-generation fuel options for your fleet',
    category: EcoPillCategory.SUSTAINABILITY,
    difficulty: EcoDifficulty.INTERMEDIATE,
    durationMin: 30,
    content: 'Overview of bioethanol, compressed natural gas, and electric alternatives. Cost-benefit analysis for transitioning fleet vehicles.',
    accessLevel: 'empresa',
    published: true,
  },
];
